### ISSUE TITLE
Specify config for spinning up VM

### ISSUE THREAD

**Issue by hweecat** [jpjeffries/database-migration-demo#11]
https://github.com/jpjeffries/database-migration-demo/blob/b0b2621fccdbf48ef3f1df95d4841a0aa9bf07d3/workshop/WorkshopGuide.txt#L33

**Scenario**
Participants might unwittingly end up spinning a Debian-based VM as it is the default OS setting when spinning up a Compute Engine VM using Cloud Console - only to realise that they can't run the rpm and yum commands.

**Solution**
Would be useful to specify/highlight the OS to use when spinning up the Compute Engine VM. Since rpm and yum are used in the command line - we can infer that the OS to use is either CentOS or RedHat.

**Comment by jpjeffries** [comment]
Done
https://github.com/jpjeffries/database-migration-demo/pull/12
