### ISSUE TITLE
Unable to spin up VM

### ISSUE THREAD

**Issue by gerardtchan** [jpjeffries/database-migration-demo#6]
https://github.com/jpjeffries/database-migration-demo/blob/86bc7f92912d30ccc94e0d1fab8285c106b56416/workshop/WorkshopGuide.txt#L16

Error:
 VERR_FILE_NOT_FOUND opening image file '<path to VM files>/CentOS7-postgres-db-migration-2-disk1.vdi'

Is the config file OS specific? I am using a windows machine. Could the "\" vs "/" conventions be causing issues?

**Comment by jpjeffries** [comment]
Hi Gerard

You may need to change the path to the VDI file in your VirtualBox settings as the folder was uploaded to the bucket from my MacBook.

<img width="486" alt="Screen Shot 2019-09-16 at 7 31 43 PM" src="https://user-images.githubusercontent.com/55126972/64954703-fce5a000-d8b8-11e9-8467-d5fbefc2c746.png">
